#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

MODEL="${MODEL:-${1:-olmo3}}"
DEFAULT_ATTENTION_BACKEND="flash"
DEFAULT_TP_SIZE="1"
DEFAULT_PP_SIZE="1"
DEFAULT_CP_SIZE="1"
case "$MODEL" in
  olmo3|olmo3-7b)
    ENTRYPOINT="$SCRIPT_DIR/train_olmo3_7b.sh"
    DEFAULT_JOB_PREFIX="pub-olmo3"
    DEFAULT_HF_MODEL_DIR="/mnt/shared-storage-gpfs2/plm-gpfs/public_data_model/model/Olmo-3-1025-7B-stage1-step1413814"
    DEFAULT_SEQ_LENGTH="8192"
    DEFAULT_MAX_POSITION_EMBEDDINGS="8192"
    DEFAULT_WINDOW_SIZE="4096,0"
    DEFAULT_WINDOW_ATTN_SKIP_FREQ="4"
    DEFAULT_MASTER_PORT="6028"
    ;;
  pythia)
    ENTRYPOINT="$SCRIPT_DIR/train_pythia.sh"
    DEFAULT_JOB_PREFIX="pub-pythia-${PYTHIA_SIZE:-160m}"
    DEFAULT_MODEL_ROOT="${MODEL_ROOT:-/mnt/shared-storage-gpfs2/plm-gpfs/public_data_model/hnet/model}"
    DEFAULT_HF_MODEL_DIR="$DEFAULT_MODEL_ROOT/pythia-${PYTHIA_SIZE:-160m}"
    DEFAULT_SEQ_LENGTH="2048"
    DEFAULT_MAX_POSITION_EMBEDDINGS="2048"
    DEFAULT_WINDOW_SIZE=""
    DEFAULT_WINDOW_ATTN_SKIP_FREQ=""
    DEFAULT_MASTER_PORT="6030"
    ;;
  *)
    echo "Unsupported MODEL=$MODEL. Use olmo3 or pythia." >&2
    exit 2
    ;;
esac

JOB_NAME="${JOB_NAME:-${DEFAULT_JOB_PREFIX}-$(date +%m%d%H%M)}"
NAMESPACE="${NAMESPACE:-ailab-plm}"
CHARGED_GROUP="${CHARGED_GROUP:-plm_gpu}"
IMAGE="${IMAGE:-registry.h.pjlab.org.cn/library/ml-base:22.04-pjlab}"
REPLICAS="${REPLICAS:-1}"
GPUS="${GPUS:-8}"
CPUS="${CPUS:-96}"
MEMORY_MB="${MEMORY_MB:-786432}"
MOUNT_CONFIG="${MOUNT_CONFIG:-gpfs://gpfs2/plm-gpfs:/mnt/shared-storage-gpfs2/plm-gpfs}"
USE_FILE_STORE="${USE_FILE_STORE:-False}"
HOST_NETWORK="${HOST_NETWORK:-true}"

RUN_ROOT="${RUN_ROOT:-/mnt/shared-storage-gpfs2/plm-gpfs/public_training_bench/runs}"
SUBMIT_ROOT="${SUBMIT_ROOT:-$RUN_ROOT/rjob_submissions}"
mkdir -p "$SUBMIT_ROOT"
SUBMIT_LOG="$SUBMIT_ROOT/submit_${JOB_NAME}.log"

host_network_args=()
if [[ "$HOST_NETWORK" == "true" || "$HOST_NETWORK" == "True" || "$HOST_NETWORK" == "1" ]]; then
  host_network_args+=(--host-network=true)
fi

rdma_args=()
if [[ "$REPLICAS" -gt 1 || "$GPUS" -ge 8 ]]; then
  rdma_args+=(--custom-resources rdma/mlnx_shared=8 --custom-resources mellanox.com/mlnx_rdma=1)
fi

negative_tag_args=()
if [[ -n "${NEGATIVE_TAGS:-}" ]]; then
  # Space-separated list, e.g. NEGATIVE_TAGS="gpu-lg-cmc-h-h200-0452.host.h.pjlab.org.cn".
  read -r -a _negative_tags <<< "$NEGATIVE_TAGS"
  negative_tag_args+=(--negative-tags "${_negative_tags[@]}")
fi

rjob_submit_help="$(rjob submit --help 2>&1 || true)"
rjob_supports() {
  grep -q -- "$1" <<< "$rjob_submit_help"
}

rjob_optional_job_args=()
if rjob_supports "--priority"; then
  rjob_optional_job_args+=(--priority "${PRIORITY:-9}")
fi
if rjob_supports "--task-type"; then
  rjob_optional_job_args+=(--task-type normal)
fi

rjob_optional_task_args=()
if rjob_supports "--image-pull-policy"; then
  rjob_optional_task_args+=(--image-pull-policy "${IMAGE_PULL_POLICY:-IfNotPresent}")
fi

echo "Submitting $JOB_NAME: model=$MODEL replicas=$REPLICAS gpus=$GPUS entrypoint=$ENTRYPOINT"
rjob submit \
  --name "$JOB_NAME" \
  --namespace "$NAMESPACE" \
  "${rjob_optional_job_args[@]}" \
  --charged-group "$CHARGED_GROUP" \
  --private-machine group \
  -P "$REPLICAS" \
  --image "$IMAGE" \
  "${rjob_optional_task_args[@]}" \
  --cpu "$CPUS" \
  --gpu "$GPUS" \
  --memory "$MEMORY_MB" \
  --share-host-shm=True \
  --use-file-store="$USE_FILE_STORE" \
  --mount "$MOUNT_CONFIG" \
  "${host_network_args[@]}" \
  "${rdma_args[@]}" \
  "${negative_tag_args[@]}" \
  -e DISTRIBUTED_JOB=true \
  -e TARGET_UID="${TARGET_UID:-10250}" \
  -e TARGET_GID="${TARGET_GID:-10250}" \
  -e TARGET_GROUPS="${TARGET_GROUPS:-10250,27,44}" \
  -e TARGET_USER="${TARGET_USER:-linzhouhan}" \
  -e RUN_ROOT="$RUN_ROOT" \
  -e RUN_NAME="${RUN_NAME:-$JOB_NAME}" \
  -e RUN_DIR="${RUN_DIR:-}" \
  -e CKPT_DIR="${CKPT_DIR:-}" \
  -e LOAD_DIR="${LOAD_DIR:-}" \
  -e PYTHIA_SIZE="${PYTHIA_SIZE:-160m}" \
  -e TRAIN_ITERS="${TRAIN_ITERS:-}" \
  -e TRAIN_SAMPLES="${TRAIN_SAMPLES:-}" \
  -e SAVE_INTERVAL="${SAVE_INTERVAL:-}" \
  -e SAVE_STEP0="${SAVE_STEP0:-0}" \
  -e LR="${LR:-}" \
  -e MIN_LR="${MIN_LR:-}" \
  -e LR_DECAY_ITERS="${LR_DECAY_ITERS:-}" \
  -e LR_DECAY_SAMPLES="${LR_DECAY_SAMPLES:-}" \
  -e LR_WARMUP_ITERS="${LR_WARMUP_ITERS:-}" \
  -e LR_WARMUP_SAMPLES="${LR_WARMUP_SAMPLES:-}" \
  -e CLIP_GRAD="${CLIP_GRAD:-}" \
  -e WEIGHT_DECAY="${WEIGHT_DECAY:-}" \
  -e OPTIMIZER="${OPTIMIZER:-}" \
  -e ADAM_BETA1="${ADAM_BETA1:-}" \
  -e ADAM_BETA2="${ADAM_BETA2:-}" \
  -e ADAM_EPS="${ADAM_EPS:-}" \
  -e USE_MOCK_DATA="${USE_MOCK_DATA:-1}" \
  -e HF_MODEL_DIR="${HF_MODEL_DIR:-$DEFAULT_HF_MODEL_DIR}" \
  -e DATA_PATH="${DATA_PATH:-}" \
  -e DATA_ARGS_PATH="${DATA_ARGS_PATH:-}" \
  -e DATA_CACHE_PATH="${DATA_CACHE_PATH:-}" \
  -e PER_DATASET_SEQUENCES_PATH="${PER_DATASET_SEQUENCES_PATH:-}" \
  -e SPLIT="${SPLIT:-}" \
  -e EVAL_ITERS="${EVAL_ITERS:-0}" \
  -e EVAL_INTERVAL="${EVAL_INTERVAL:-1000}" \
  -e MMAP_BIN_FILES="${MMAP_BIN_FILES:-1}" \
  -e DATALOADER_FAST_CACHE_LOAD="${DATALOADER_FAST_CACHE_LOAD:-0}" \
  -e DATALOADER_DEFER_NPY_INDEX_MMAP="${DATALOADER_DEFER_NPY_INDEX_MMAP:-0}" \
  -e SEQ_LENGTH="${SEQ_LENGTH:-$DEFAULT_SEQ_LENGTH}" \
  -e MAX_POSITION_EMBEDDINGS="${MAX_POSITION_EMBEDDINGS:-$DEFAULT_MAX_POSITION_EMBEDDINGS}" \
  -e MAKE_VOCAB_SIZE_DIVISIBLE_BY="${MAKE_VOCAB_SIZE_DIVISIBLE_BY:-}" \
  -e GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-128}" \
  -e MICRO_BATCH_SIZE="${MICRO_BATCH_SIZE:-1}" \
  -e TP_SIZE="${TP_SIZE:-$DEFAULT_TP_SIZE}" \
  -e PP_SIZE="${PP_SIZE:-$DEFAULT_PP_SIZE}" \
  -e CP_SIZE="${CP_SIZE:-$DEFAULT_CP_SIZE}" \
  -e GPUS_PER_NODE="${GPUS_PER_NODE:-$GPUS}" \
  -e MASTER_PORT="${MASTER_PORT:-$DEFAULT_MASTER_PORT}" \
  -e ATTENTION_BACKEND="${ATTENTION_BACKEND:-$DEFAULT_ATTENTION_BACKEND}" \
  -e TRANSFORMER_IMPL="${TRANSFORMER_IMPL:-transformer_engine}" \
  -e INIT_METHOD_VARIANT="${INIT_METHOD_VARIANT:-}" \
  -e OLMO3_LAYER_SPEC_MODULE="${OLMO3_LAYER_SPEC_MODULE:-}" \
  -e OLMO3_LAYER_SPEC_NAME="${OLMO3_LAYER_SPEC_NAME:-}" \
  -e WINDOW_SIZE="${WINDOW_SIZE:-$DEFAULT_WINDOW_SIZE}" \
  -e WINDOW_ATTN_SKIP_FREQ="${WINDOW_ATTN_SKIP_FREQ:-$DEFAULT_WINDOW_ATTN_SKIP_FREQ}" \
  -e OLMO3_QK_NORM_IMPL="${OLMO3_QK_NORM_IMPL:-te}" \
  -e OLMO3_LOCAL_FLASH_IMPL="${OLMO3_LOCAL_FLASH_IMPL:-fa3}" \
  -e OLMO3_Z_LOSS_MULTIPLIER="${OLMO3_Z_LOSS_MULTIPLIER:-0}" \
  -e OLMO3_EMBEDDING_WEIGHT_DECAY_ZERO="${OLMO3_EMBEDDING_WEIGHT_DECAY_ZERO:-0}" \
  -e GRAD_REDUCE_IN_BF16="${GRAD_REDUCE_IN_BF16:-1}" \
  -e OVERLAP_PARAM_GATHER="${OVERLAP_PARAM_GATHER:-1}" \
  -e SAVE_FULL_STATE="${SAVE_FULL_STATE:-0}" \
  -e EMPTY_UNUSED_MEMORY_LEVEL="${EMPTY_UNUSED_MEMORY_LEVEL:-0}" \
  -e MANUAL_GC_INTERVAL="${MANUAL_GC_INTERVAL:-10}" \
  -e ENABLE_MUDD_TORCH_COMPILE="${ENABLE_MUDD_TORCH_COMPILE:-}" \
  -e ENABLE_CONCEPTLM_V21_DECODER_TORCH_COMPILE="${ENABLE_CONCEPTLM_V21_DECODER_TORCH_COMPILE:-}" \
  -e CONCEPTLM_V21_FORCE_SCALAR_ROUTES="${CONCEPTLM_V21_FORCE_SCALAR_ROUTES:-}" \
  -e CONCEPTLM_V21_LEGACY_SCALAR_ROUTE_LOAD="${CONCEPTLM_V21_LEGACY_SCALAR_ROUTE_LOAD:-}" \
  -e CONCEPTLM_V21_DIAG_ROUTE_PROJ="${CONCEPTLM_V21_DIAG_ROUTE_PROJ:-}" \
  -e CONCEPTLM_V21_ACTIVE_ONLY_ROUTES="${CONCEPTLM_V21_ACTIVE_ONLY_ROUTES:-}" \
  -e CONCEPTLM_V21_SELF_DD_UNSTACKED_FASTPATH="${CONCEPTLM_V21_SELF_DD_UNSTACKED_FASTPATH:-1}" \
  -e CONCEPTLM_V21_ROUTE_FIRST_PLUS_LAST_N="${CONCEPTLM_V21_ROUTE_FIRST_PLUS_LAST_N:-}" \
  -e CONCEPTLM_V21_DD_TWO_ROUTE_ADD_DECODER_USE_SOFTMAX="${CONCEPTLM_V21_DD_TWO_ROUTE_ADD_DECODER_USE_SOFTMAX:-}" \
  -e CONCEPTLM_V21_CE_DEBUG="${CONCEPTLM_V21_CE_DEBUG:-}" \
  -e CONCEPTLM_V21_CE_DEBUG_EVERY_N="${CONCEPTLM_V21_CE_DEBUG_EVERY_N:-}" \
  -e CONCEPTLM_V21_CE_DEBUG_MAX_BAD_TOKENS="${CONCEPTLM_V21_CE_DEBUG_MAX_BAD_TOKENS:-}" \
  -e CONCEPTLM_V21_LOSS_DEBUG_MAX_BAD="${CONCEPTLM_V21_LOSS_DEBUG_MAX_BAD:-}" \
  -e CONCEPTLM_V21_FINITE_DEBUG="${CONCEPTLM_V21_FINITE_DEBUG:-}" \
  -e CONCEPTLM_V21_FINITE_DEBUG_START_ITER="${CONCEPTLM_V21_FINITE_DEBUG_START_ITER:-}" \
  -e CONCEPTLM_V21_FINITE_DEBUG_END_ITER="${CONCEPTLM_V21_FINITE_DEBUG_END_ITER:-}" \
  -e CONCEPTLM_V21_FINITE_DEBUG_FATAL="${CONCEPTLM_V21_FINITE_DEBUG_FATAL:-}" \
  -e CONCEPTLM_V21_FINITE_DEBUG_MAX_BAD="${CONCEPTLM_V21_FINITE_DEBUG_MAX_BAD:-}" \
  -e CONCEPTLM_V21_TRACE_DEBUG="${CONCEPTLM_V21_TRACE_DEBUG:-}" \
  -e CONCEPTLM_V21_TRACE_DEBUG_ABS_THRESHOLD="${CONCEPTLM_V21_TRACE_DEBUG_ABS_THRESHOLD:-}" \
  -e CONCEPTLM_V21_TRACE_DEBUG_MAX_POS="${CONCEPTLM_V21_TRACE_DEBUG_MAX_POS:-}" \
  -e CONCEPTLM_V21_ACTIVATION_DEBUG="${CONCEPTLM_V21_ACTIVATION_DEBUG:-}" \
  -e CONCEPTLM_V21_ACTIVATION_DEBUG_START_ITER="${CONCEPTLM_V21_ACTIVATION_DEBUG_START_ITER:-}" \
  -e CONCEPTLM_V21_ACTIVATION_DEBUG_END_ITER="${CONCEPTLM_V21_ACTIVATION_DEBUG_END_ITER:-}" \
  -e CONCEPTLM_V21_ACTIVATION_DEBUG_ABS_THRESHOLD="${CONCEPTLM_V21_ACTIVATION_DEBUG_ABS_THRESHOLD:-}" \
  -e CONCEPTLM_V21_ACTIVATION_DEBUG_MAX_ROWS="${CONCEPTLM_V21_ACTIVATION_DEBUG_MAX_ROWS:-}" \
  -e CONCEPTLM_V21_ACTIVATION_DEBUG_TAGS="${CONCEPTLM_V21_ACTIVATION_DEBUG_TAGS:-}" \
  -e CONCEPTLM_V22_VQ_CE_DEBUG="${CONCEPTLM_V22_VQ_CE_DEBUG:-}" \
  -e CONCEPTLM_V22_VQ_CE_DEBUG_EVERY_N="${CONCEPTLM_V22_VQ_CE_DEBUG_EVERY_N:-}" \
  -e CONCEPTLM_V22_VQ_CE_DEBUG_MAX_BAD_TOKENS="${CONCEPTLM_V22_VQ_CE_DEBUG_MAX_BAD_TOKENS:-}" \
  -e MUDD_TORCH_COMPILE_BACKEND="${MUDD_TORCH_COMPILE_BACKEND:-}" \
  -e MUDD_TORCH_COMPILE_MODE="${MUDD_TORCH_COMPILE_MODE:-}" \
  -e MUDD_TORCH_COMPILE_FULLGRAPH="${MUDD_TORCH_COMPILE_FULLGRAPH:-}" \
  -e MUDD_TORCH_COMPILE_DYNAMIC="${MUDD_TORCH_COMPILE_DYNAMIC:-}" \
  -e CONCEPTLM_V21_ROUTE_TORCH_COMPILE_BACKEND="${CONCEPTLM_V21_ROUTE_TORCH_COMPILE_BACKEND:-}" \
  -e CONCEPTLM_V21_ROUTE_TORCH_COMPILE_MODE="${CONCEPTLM_V21_ROUTE_TORCH_COMPILE_MODE:-}" \
  -e CONCEPTLM_V21_ROUTE_TORCH_COMPILE_FULLGRAPH="${CONCEPTLM_V21_ROUTE_TORCH_COMPILE_FULLGRAPH:-}" \
  -e CONCEPTLM_V21_ROUTE_TORCH_COMPILE_DYNAMIC="${CONCEPTLM_V21_ROUTE_TORCH_COMPILE_DYNAMIC:-}" \
  -e TRAIN_ENTRYPOINT="${TRAIN_ENTRYPOINT:-}" \
  -e CALCULATE_PER_TOKEN_LOSS="${CALCULATE_PER_TOKEN_LOSS:-}" \
  -e FUSED_RESIDUAL_RMSNORM="${FUSED_RESIDUAL_RMSNORM:-}" \
  -e ENABLE_WANDB="${ENABLE_WANDB:-1}" \
  -e WANDB_MODE="${WANDB_MODE:-offline}" \
  -e WANDB_PROJECT="${WANDB_PROJECT:-ConceptLM}" \
  -e WANDB_EXP_NAME="${WANDB_EXP_NAME:-$JOB_NAME}" \
  -e WANDB_ENTITY="${WANDB_ENTITY:-iammi-nanjing-university}" \
  -e WANDB_API_KEY="${WANDB_API_KEY:-}" \
  -e WANDB_DISABLE_CODE="${WANDB_DISABLE_CODE:-true}" \
  -e WANDB_SILENT="${WANDB_SILENT:-true}" \
  -e HIDDEN_RANK_LOG_INTERVAL="${HIDDEN_RANK_LOG_INTERVAL:-500}" \
  -e HIDDEN_RANK_LOG_TOKENS="${HIDDEN_RANK_LOG_TOKENS:-1024}" \
  -e HIDDEN_RANK_RTOL="${HIDDEN_RANK_RTOL:-1e-3}" \
  -e HIDDEN_RANK_CENTER="${HIDDEN_RANK_CENTER:-1}" \
  -e RERUN_MODE="${RERUN_MODE:-disabled}" \
  -e NVTE_DEBUG="${NVTE_DEBUG:-0}" \
  -e NVTE_DEBUG_LEVEL="${NVTE_DEBUG_LEVEL:-0}" \
  -e EXTRA_ARGS="${EXTRA_ARGS:-}" \
  -- bash "$ENTRYPOINT" | tee "$SUBMIT_LOG"

METADATA_NAME="$(sed -n 's/.*created rjob_name: //p' "$SUBMIT_LOG" | tail -n 1)"
if [[ -z "$METADATA_NAME" ]]; then
  METADATA_NAME="$JOB_NAME"
fi

{
  echo "date=$(date -Is)"
  echo "job_name=$JOB_NAME"
  echo "metadata_name=$METADATA_NAME"
  echo "model=$MODEL"
  echo "entrypoint=$ENTRYPOINT"
  echo "repo_root=$REPO_ROOT"
  echo "submit_log=$SUBMIT_LOG"
  rjob get "$METADATA_NAME" --namespace "$NAMESPACE" || true
} > "$SUBMIT_ROOT/status_${JOB_NAME}.txt" 2>&1

echo "$METADATA_NAME" > "$SUBMIT_ROOT/last_${MODEL}.job"
echo "metadata_name=$METADATA_NAME"
